### ISSUE TITLE
Ghost Army

### ISSUE THREAD

**Issue by pjd79** [FutureShockco/drugwars.io#103]
### Expected behavior
without any units, I should not have any defense
### Actual behavior
While I have no units, I have a defense with units that I do not have.
![2019-07-20-143956_1366x768_scrot](https://user-images.githubusercontent.com/48220409/61578813-992f3880-aafc-11e9-8c96-2f66c0dc4a47.png)

It is the following of bug [102](https://github.com/FutureShockco/drugwars.io/issues/102)

The négative quantity of units in the bootcamp is now fixed. But it's been two days since I lost any units, which may be the cause of that

### Steps to reproduce the behavior
I don't know if this bug can be reproduced

**Comment by hightouch67** [comment]
Well, you had troops stationed there coming from another account since two days.

So this is not a bug I think or I have missed something.

I will try to display the name of the troops owner so you clearly see which units are yours.

**Comment by pjd79** [comment]
It did not happen anymore.
So I consider the problem as fixed

**Comment by pjd79** [comment]
I reopen the issue because I have a new stange report
![2019-07-31-002800_1366x768_scrot](https://user-images.githubusercontent.com/48220409/62170021-3757a580-b32a-11e9-8aab-2ab2630f1978.png).
I do not have so many units and the line summarizing the available units seems to me strange

**Comment by pjd79** [comment]
Another strange report
![2019-08-02-144550_1366x768_scrot](https://user-images.githubusercontent.com/48220409/62371230-94bf4280-b534-11e9-89e6-f8e31722ad68.png)

**Comment by pjd79** [comment]
It seems fixed. No new strange report.
