### ISSUE TITLE
Site is slow, please move the app to a CDN

### ISSUE THREAD

**Issue by Vheissu** [FutureShockco/drugwars.io#23]
The Drug Wars site is extremely slow to load. Investigation in the network tab seems to indicate long-loading times for simple assets. Although HTTP/2 is being used and multiplexing comes into the equation, I am seeing 1s+ loading times for basic assets and scripts.

A site like this can be completely hosted on a CDN and massively distributed/cached on something like AWS Cloudfront. This is a huge source of frustration, please address this issue first before anything else.

Even after the browser caches the static resources initially, it appears the call to `api.steemit.com` is a serious bottleneck in the application.

**Comment by bonustrack** [comment]
This issue has been resolved, there was too much request on the API, it was overloading the database.

**Comment by Vheissu** [comment]
@bonustrack Can confirm that the site feels faster. I am going to close this issue. Thanks for the continual improvement.
