### ISSUE TITLE
A illogical fight

### ISSUE THREAD

**Issue by pjd79** [FutureShockco/drugwars.io#35]
How a fight can have this type of result?
![battle-bug](https://user-images.githubusercontent.com/48220409/54056429-56755f80-41f0-11e9-81a4-87f599489412.png)

It will be good if we have explanation of the rules of the batlles.
because, in this example,  it is incomprehensible and illogical to me a

**Comment by pjd79** [comment]
Finally, I understood the color code in the display of the results of a fight. But it is not clear to have in white the total number of units when they received no damage and in red the number of units killed during the fight.

**Comment by bonustrack** [comment]
This fight happen in 1 turn, the rowdy of the attacker deal damages to the opposite rowdys, one of them die. The target units attack the attacker rowdy and he die.

Here is some comprehensible guide on how battle work: https://steemit.com/drugwars/@timcliff/drug-wars-on-steem-intermediate-game-guide-battles 

How do you want we display dead and total units?

**Comment by pjd79** [comment]
What disturbed me is that, for example for knifer, I have the number of surviving units and for the rowdy, I have the number of units lost, on the same line. 
Which made the interpretation difficult for me.
This presentation has the advantage of being synthetic but not intuitive for me, two different and opposite types of meanings  being given for the numbers. If there is a red number and a slash under the icon of the unit, it indicates the quantity of  units lost; if not, it indicates that there is no dead for this type of units and the number represents the total of units who have participated to the fight.

Personally, I will put the number of remaining units after the fight, with the number of initial units noted after the slash. In that way, it would be consistent across the line.

After that, it's just a detail and now I've learned to read the combat report.

**Comment by pjd79** [comment]
I now understand how the results of the fights are displayed. I close the bug, it seems to me to be a detail.
