### ISSUE TITLE
daily payment bug

### ISSUE THREAD

**Issue by Azemblage** [FutureShockco/drugwars.io#42]
### Expected behavior
So I have been playing the game and usually the daily payment is done correctly and after been transfer, it starts to go down. That would be the correct and expected behavior 

### Actual behavior
I have grown my daily amount after all the payments have been done. After a couple of hours on the same day, I found out that even without any payment transfer done it was shrinking and less. So there is a problem and it is taking out daily payments without transfer.

_____________
I attach images of the problem below:

date 2019-03-16 - time 04:34:55:
![date 2019-03-16 - time 04 34 55](https://user-images.githubusercontent.com/47430066/54476977-1f5c0b00-47fb-11e9-9d10-d10870760ba5.png)

date 2019-03-16 - time 14:29:57 (without any transfer start to shrink):
![date 2019-03-16 - time 14 29 57](https://user-images.githubusercontent.com/47430066/54476984-2edb5400-47fb-11e9-88fd-28a1461ee544.png)

**Comment by bonustrack** [comment]
The amount displayed is dynamic, it's normal if there is some small change on the same day. Dont you get the reward daily?

**Comment by Azemblage** [comment]
I receive it daily, except one day that it wasn't paid at midnight but just received at 3 AM. But the issue is not that the daily pay only goes down after the payment of the day is done and now is shrinking all the time. 

You can see below on the same day without payment and shrink another digit...
![Captura de ecrã 2019-03-16, às 17 24 53](https://user-images.githubusercontent.com/47430066/54479207-7caf8680-4812-11e9-82dc-469373b349c6.png)

This is a pretty big bug here because if I gather resources and all that and the daily payment is getting lower without any transfer, where it's going?

**Comment by hightouch67** [comment]
As @bonustrack said, the daily payment is also dynamic and you get a % of the total daily pool depending on how much drugs you produce. So if other players upgrade their drug production and you dont, this will allways go lower day by day.

**Comment by Azemblage** [comment]
@hightouch67 that never happen since now. The only dynamic % I saw doing that is the heist part of the money payments. You are saying that the daily payment was always like that? Because the only issue I am having was just today... that drop 4 points there in the images.

**Comment by Azemblage** [comment]
After yesterday payment was done... it went down over 8 points. I don't know what is happening but this is getting problematic. You should explain and discriminate in dept the way you are doing those cuts there because something is not adding up. 

We gather resources and purchase buildings playing far and then have a lot cut down in just one day.. that is not right - there is something happen here. Have a look at this and fix it.

date 2019-03-17 - time 13:02:36( this is becoming a joke now... it goes down faster then when I buy buildings up..):
![Captura de ecrã 2019-03-17, às 13 02 36](https://user-images.githubusercontent.com/47430066/54493188-d4a6c580-48c4-11e9-880e-bfdf7ef37015.png)
