### ISSUE TITLE
Suggestion to improve UX

### ISSUE THREAD

**Issue by HarryHeights** [FutureShockco/drugwars.io#43]
I've been thinking. Maybe not a lot though. This idea is just roughly thought. But wouldn't it be a great thing if I can have a friend send stuffs. Like drugs, guns and alcohol. I don't think this is impossible to implement. 
Aside from that, it would be great if I can ask my friends to lend me units for a battle. 

For example I've got three friends. 4 of us combined got great resources and we attack someone and split the resources afterwards if we win. 

What do you think about this idea?

**Comment by mys** [comment]
Bots and multiaccounts will send resources to one account then (pushing). I don't think that would be fair.

**Comment by HarryHeights** [comment]
That's true though. I'm not so much tech inclined but isn't there a way to fight bots?

**Comment by hightouch67** [comment]
We want to implement the resource transport, with the "transporter unit".

But as @mys said, it will probably push people to make many accounts so you should be able to only send resources to a player with lower production.

Stay tuned for more informations about the transporter unit ;)
