### ISSUE TITLE
Attacked 2 players but didnt get my steel

### ISSUE THREAD

**Issue by tizoy1984** [FutureShockco/drugwars.io#54]
### Expected behavior
What I steel from another player I should get to my balance
### Actual behavior
Not added to my balance
### Steps to reproduce the behavior
![Naamloos](https://user-images.githubusercontent.com/4014995/55324636-fb4b2b80-5482-11e9-8f8c-f7df28541887.png)

As you can see in the pic...all that I stole didnt add up to my balance

**Comment by catmia** [comment]
the same...

**Comment by hightouch67** [comment]
Hey I close this issue, it was related to the update of the first april and it has been fixed since.
