### ISSUE TITLE
The training facility does not decrease in a significative way the time needed to recruit troops

### ISSUE THREAD

**Issue by pjd79** [FutureShockco/drugwars.io#67]
### Expected behavior
The upgrade of the training facility must decrease the time to build the units

### Actual behavior
This is not currently the case.

### Steps to reproduce the behavior
Upgrade the training facility and see that the time to upgrade an unit has not changed.

**Comment by pjd79** [comment]
After checking and upgrading through the training facility to level 9, the upgrade has an impact but too small to be significant: a on -second decrease in the recruitment time of a unit, whatever the unit.
It seems insignificant and therefore this building seems to me to lose its usefulness.

It would seem to me more appropriate that this decrease be in percentage on the time of recruitment of each unit.

**Comment by pjd79** [comment]
There seems to be the same problem with the research center

**Comment by hightouch67** [comment]
Thanks a lot again for your contribution, even if I reply lately, this issue was adressed earlier and the training facility is giving now more reduction when you upgrade it.
