### ISSUE TITLE
OUTGOING FIGHT always stays in "PREPARATION"

### ISSUE THREAD

**Issue by neomis78** [FutureShockco/drugwars.io#69]
I cannot battle any more as I have a pending fight, it has been this way for some time and seems stuck (waiting for confirmation)

Username NEOMIS

**Comment by windenchanter** [comment]
Same here. I am also stuck. Username Windenchanter

**Comment by josexp** [comment]
I have the same problem username rollxp

**Comment by neomis78** [comment]
this morning was ok, now it's "IN  PREPARATION" again!!
