### ISSUE TITLE
Psychological Training too efficient for defense

### ISSUE THREAD

**Issue by pjd79** [FutureShockco/drugwars.io#82]
### Expected behavior
Each level increase  the defense of your Mercenaries by 0.1%.

### Actual behavior
It's not the case.
See in  this extract of a fight opposing a mercenary and a big mama with level 1 psychological training for the mercenary

> [A] mercenary (1) with 7500 HP take 599 DMG from [D] big_mama (1) with "groupheal". [A] mercenary (1) got now 6901 HP.

It seems to be linked to the line 97 of army.js  ( https://github.com/FutureShockco/drugwars.js/blob/99b1f379ca764050e6b07ac56e396a00abf88163/src/army.js#L97) 
          `    unit.defense = unit.defense + unit.attack /100 *psychological.lvl;`

It must be 
          `    unit.defense = unit.defense + unit.defense /100 *psychological.lvl;`

### Steps to reproduce the behavior
Make a fight between a mercenary and any unit with and  without psychological training and see the difference.

**Comment by pjd79** [comment]
Same problem for the ninja , but with less impact because of the lower attack power
For example, this extract of a fight versus a gunman and a ninja at level 10 of psychological training.

> [D] ninja (1) with 3000 HP take 1060 DMG from [A] gunman (1) with "accuratehit". [D] ninja (1) took 106 DMG bonus. [D] ninja (1) got now 1834 HP.

**Comment by hightouch67** [comment]
ah totaly my bad... I even missed it with the last update. I will fix it later. Thanks a lot!

**Comment by hightouch67** [comment]
it should be ok now, the formula is now the following one
![image](https://user-images.githubusercontent.com/24254887/57532318-ed62b300-732a-11e9-8609-027efa01deaf.png)

**Comment by pjd79** [comment]
There is always a bug, but now this training is ineffective for the defense.
I open a new bug: #88 
 because this does not seem to be related to the same cause.
