### ISSUE TITLE
Safe and capacity of storage are no longer correct in the overview page or in the front bar

### ISSUE THREAD

**Issue by pjd79** [FutureShockco/drugwars.io#85]
### Expected behavior
Safe and capacity of storage must be identical to what they are in the description of the storage buildings

### Actual behavior
With the last update, safe and capacity of storage has changed and so the formula to calculate it.  And that's a good thing !!!!!
But this change was not propagated in the rest of the code
I have found this problem in 4 files after a query on github.
The affected files are:

- https://github.com/FutureShockco/drugwars.io/blob/b0275c6fd65ab9fc66a6b79b890c1cd195b47d91/src/views/Overview.vue
-https://github.com/FutureShockco/drugwars.io/blob/08f0aa2451d6cdb301e2bf2199a349a5072b2f1c/src/components/Fights/Detail.vue
- https://github.com/FutureShockco/drugwars.io/blob/733a0c71b00c6cca830c52329466dee6b34981c6/src/views/User.vue
- https://github.com/FutureShockco/drugwars.io/blob/8d9b9a70d4b8995cff060f33a85b678c41680df5/src/components/Balances.vue

### Steps to reproduce the behavior
Open building page and compare the value of the safe and the capacity of storage in this page with the other part of the interface where it is displayed

**Comment by hightouch67** [comment]
Hey this is related to last change where I have upgraded the storage limits.

Players have to upgrade their storage at least one time to have the new values everywhere.

**Comment by pjd79** [comment]
Thank you for the response.
 I understand better the reason of that.

**Comment by pjd79** [comment]
Adjusted after the upgrade of the storage. I close the issue.
