### ISSUE TITLE
Proposal new logo

### ISSUE THREAD

**Issue by riyandacountri** [FutureShockco/drugwars.io#90]
Hi Admin! I want to offer a new logo for drugwars.io

![7](https://user-images.githubusercontent.com/37598141/57715052-0909e880-76a0-11e9-9201-0c4dc193e297.png)

If you like it and want to use it, I can send the complete file. Thanks!

**Comment by hightouch67** [comment]
hey thanks a lot for the proposal but we decided to keep what we already have.
