### ISSUE TITLE
Is it normal that rowdies attack in group and defend separately ?

### ISSUE THREAD

**Issue by pjd79** [FutureShockco/drugwars.io#94]
### Expected behavior
Rowdies attack and defend in the same way
### Actual behavior
Rowdies attacks in group and defend separately.
An example of a fight between 4 rowdies and 4 rowdies in DrugWars fight simulator v0.0.76

> [D] rowdy (1) with 300.00 HP and 40 DEF take 760 DMG from [A] rowdy (0) with "group". [D] rowdy (1) is now dead.
> 
> [A] group (0) with 4 x rowdy with 1040.000 HP take 160 DMG from [D] rowdy (1) with "group".
> 
> [A] group (0) with 4 x rowdy with 880.000 HP take 160 DMG from [D] rowdy (2) with "group". [A] 3 x rowdy group (0) are left.
> 
> [A] group (0) with 3 x rowdy with 720.000 HP take 160 DMG from [D] rowdy (3) with "group".
> 
> [A] group (0) with 3 x rowdy with 560.000 HP take 160 DMG from [D] rowdy (4) with "group". [A] 2 x rowdy group (0) are left.

### Steps to reproduce the behavior
Make the same simulation

**Comment by hightouch67** [comment]
definitely not normal, thanks a lot for pointing it out!!

**Comment by hightouch67** [comment]
it should be fixed now! again thanks for the help!
