### ISSUE TITLE
Lost Tokens

### ISSUE THREAD

**Issue by DiamondCreel** [FutureShockco/drugwars.io#96]
Hi,
I don't receiving future tokens for about 1 month. I should receive 4 future per day actually, and nether the heist works. Please fix. If i don't receive my payments, for what i play?

**Comment by hightouch67** [comment]
hey @DiamondCreel 
Don't hesitate to contact me on discord with your username/nickname and I will solve your issue.
https://discord.me/drugwars

**Comment by DiamondCreel** [comment]
i don't receiving any tokens for over a month. My actually name in game is Diamond. Please fix it.
