### ISSUE TITLE
All my army disappeared after a battle that I win....

### ISSUE THREAD

**Issue by Azemblage** [FutureShockco/drugwars.io#97]
### Expected behavior
After a battle when you win your army returns to the Bootcamp
### Actual behavior
After the battle, I win and my army didn't return to the Bootcamp. They disappeared and don't know how to get them back... Already try to logout and login again and nothing appears back.
### Steps to reproduce the behavior
Just did a normal fight and win I don't know if it was on the time of any maintenance or something but this bug is bad for the game since even if you win you end up losing everyone on your army...

**Comment by hightouch67** [comment]
Hi @Azemblage this is definitely not normal and I suggest you to contact me on discord to get your units back.
https://discord.me/drugwars

**Comment by Azemblage** [comment]
Thanks, @hightouch67 I will be reaching you there. To see if we can figure it out
