### ISSUE TITLE
Token blocked

### ISSUE THREAD

**Issue by DiamondCreel** [FutureShockco/drugwars.io#99]
i don't receiving any tokens for over a month. My actually name in game is Diamond. Please fix it.

**Comment by DiamondCreel** [comment]
Where is my token?? I'm blocked at 205 future for over a month!!! Today i should earn 13 future!
My name in game in diamond. Fix it!!

**Comment by hightouch67** [comment]
Well your issue should be fixed now. Can you confirm it? thanks!

**Comment by DiamondCreel** [comment]
yeah now it's ok thanks a lot!
